[package]
name = "burner_watcher"
version = "0.1.0"
authors = ["Tim Sweeney <mainetim@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gpio-cdev = "0.2"
chrono = "0.4"
toml = "0.5"
